version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Desafio_Jogo_De_Baralho/Dockerfile
    image: desafio_jogo_de_baralho_api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  tests:
    build:
      context: .
      dockerfile: Desafio_Jogo_De_Baralho_Testes/Dockerfile
    image: desafio_jogo_de_baralho_tests
    depends_on:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: ["dotnet", "test"]