version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Desafio_Jogo_De_Baralho/Dockerfile
    image: desafio_jogo_de_baralho_api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  tests:
    build:
      context: .
      dockerfile: Desafio_Jogo_De_Baralho_Testes/Dockerfile
    image: desafio_jogo_de_baralho_tests
    depends_on:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./logs:/app/logs
      - ./TestResults:/app/Desafio_Jogo_De_Baralho_Testes/TestResults
    command: ["sh", "-c", "dotnet test --logger:trx;LogFileName=TestResults/test_results.trx && cat TestResults/test_results.trx"]

  frontend:
    build:
      context: ./desafio-jogo-de-baralho-frontend
      dockerfile: Dockerfile
    image: desafio_jogo_de_baralho_frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://api:5000